/**
 * Generates the PrimeVue v4 "Aura" design-token layer as a Sass partial of
 * CSS custom properties (`--p-*`), scoped so that the dark color scheme is
 * activated by Quasar's `body.body--dark` selector.
 *
 * The output is produced by PrimeVue's own theming engine (`@primeuix/styled`
 * + `@primeuix/themes`), so the values stay faithful to the upstream Aura
 * preset and can be regenerated whenever PrimeVue is upgraded:
 *
 *     node tools/generate-tokens.mjs
 *
 * The result is written to `src/css/primevue/_tokens.scss`.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Theme, ThemeUtils } from '@primeuix/styled';
import Aura from '@primeuix/themes/aura';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, '../src/css/primevue/_tokens.scss');

// Quasar toggles dark mode via `body.body--dark`; align PrimeVue's dark
// color-scheme selector with it so a single class flips the whole palette.
const DARK_SELECTOR = '.body--dark';

// Components whose token sets are emitted. The common (primitive + semantic +
// global) variables are always included; this list controls which per-component
// `--p-<component>-*` variables are generated. Extend it as more Quasar
// components are themed.
const COMPONENTS = [
  'button',
  'inputtext',
  'textarea',
  'select',
  'multiselect',
  'checkbox',
  'radiobutton',
  'toggleswitch',
  'card',
  'chip',
  'badge',
  'tag',
  'message',
  'divider',
  'progressbar',
  'slider',
  'tabs',
  'listbox',
  'menu',
  'dialog',
  'tooltip',
  'toolbar',
  'panel',
  'paginator',
];

Theme.setTheme({
  preset: Aura,
  options: { prefix: 'p', darkModeSelector: DARK_SELECTOR, cssLayer: false },
});

function stripStyleTags(html) {
  return html.replace(/<style[^>]*>/g, '\n').replace(/<\/style>/g, '\n');
}

const commonCss = stripStyleTags(Theme.getCommonStyleSheet('', {}, {}));

let componentCss = '';
for (const name of COMPONENTS) {
  if (!Aura.components || !Aura.components[name]) {
    console.warn(`! Skipping unknown Aura component: ${name}`);
    continue;
  }
  const result = ThemeUtils.getPresetC({
    name,
    theme: Theme.getTheme(),
    params: undefined,
    set: undefined,
    defaults: Theme.defaults,
  });
  if (result && result.css) {
    componentCss += `\n/* ${name} */\n${result.css}\n`;
  }
}

const header = `// =============================================================================
// DO NOT EDIT BY HAND.
// Generated by tools/generate-tokens.mjs from the PrimeVue v4 "Aura" preset
// (@primeuix/themes). Run \`node tools/generate-tokens.mjs\` to regenerate.
//
// Exposes PrimeVue's design tokens as CSS custom properties (\`--p-*\`).
// The dark color scheme is bound to Quasar's \`body.body--dark\` selector.
// =============================================================================
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, `${header}\n/* Common: primitive + semantic + global */\n${commonCss}\n${componentCss}`);

console.log(`Wrote ${OUT} (${COMPONENTS.length} components).`);
