/**
 * Generates the PrimeVue v4 design-token layers as Sass partials of CSS custom
 * properties (`--p-*`), scoped so that the dark color scheme is activated by
 * Quasar's `body.body--dark` selector.
 *
 * A partial is produced for every supported preset (Aura, Material, Lara,
 * Nora). The component overrides in `src/css/components` are written against
 * these `--p-*` tokens, so swapping the token layer re-themes the whole Quasar
 * app — which is how the playground switches themes at runtime.
 *
 * The output is produced by PrimeVue's own theming engine (`@primeuix/styled`
 * + `@primeuix/themes`), so the values stay faithful to the upstream presets
 * and can be regenerated whenever PrimeVue is upgraded:
 *
 *     node tools/generate-tokens.mjs
 *
 * Aura is written to `src/css/primevue/_tokens.scss` (kept for back-compat);
 * the other presets are written to `_tokens-<preset>.scss` in the same folder.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Theme, ThemeUtils } from '@primeuix/styled';
import Aura from '@primeuix/themes/aura';
import Material from '@primeuix/themes/material';
import Lara from '@primeuix/themes/lara';
import Nora from '@primeuix/themes/nora';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '../src/css/primevue');

// Quasar toggles dark mode via `body.body--dark`; align PrimeVue's dark
// color-scheme selector with it so a single class flips the whole palette.
const DARK_SELECTOR = '.body--dark';

// The presets to emit. Aura keeps the canonical `_tokens.scss` filename; the
// rest are suffixed. Order is cosmetic.
const PRESETS = [
  { name: 'aura', preset: Aura, file: '_tokens.scss' },
  { name: 'material', preset: Material, file: '_tokens-material.scss' },
  { name: 'lara', preset: Lara, file: '_tokens-lara.scss' },
  { name: 'nora', preset: Nora, file: '_tokens-nora.scss' },
];

// Components whose token sets are emitted. The common (primitive + semantic +
// global) variables are always included; this list controls which per-component
// `--p-<component>-*` variables are generated. Extend it as more Quasar
// components are themed.
const COMPONENTS = [
  'button',
  'inputtext',
  'textarea',
  'select',
  'multiselect',
  'checkbox',
  'radiobutton',
  'toggleswitch',
  'card',
  'chip',
  'badge',
  'tag',
  'message',
  'divider',
  'progressbar',
  'slider',
  'tabs',
  'listbox',
  'menu',
  'dialog',
  'tooltip',
  'toolbar',
  'panel',
  'paginator',
  // Phase 4 — components Quasar lacks, built under src/components.
  'metergroup',
  'fieldset',
  'inplace',
  'dataview',
  'orderlist',
  'picklist',
  // Phase 4 — second iteration (P2 components).
  'password',
  'blockui',
  'popover',
];

function stripStyleTags(html) {
  return html.replace(/<style[^>]*>/g, '\n').replace(/<\/style>/g, '\n');
}

function buildHeader(name) {
  return `// =============================================================================
// DO NOT EDIT BY HAND.
// Generated by tools/generate-tokens.mjs from the PrimeVue v4 "${name}" preset
// (@primeuix/themes). Run \`node tools/generate-tokens.mjs\` to regenerate.
//
// Exposes PrimeVue's design tokens as CSS custom properties (\`--p-*\`).
// The dark color scheme is bound to Quasar's \`body.body--dark\` selector.
// =============================================================================
`;
}

function generate({ name, preset, file }) {
  Theme.setTheme({
    preset,
    options: { prefix: 'p', darkModeSelector: DARK_SELECTOR, cssLayer: false },
  });

  const commonCss = stripStyleTags(Theme.getCommonStyleSheet('', {}, {}));

  let componentCss = '';
  for (const component of COMPONENTS) {
    if (!preset.components || !preset.components[component]) {
      console.warn(`! [${name}] Skipping unknown component: ${component}`);
      continue;
    }
    const result = ThemeUtils.getPresetC({
      name: component,
      theme: Theme.getTheme(),
      params: undefined,
      set: undefined,
      defaults: Theme.defaults,
    });
    if (result && result.css) {
      componentCss += `\n/* ${component} */\n${result.css}\n`;
    }
  }

  const out = path.join(OUT_DIR, file);
  fs.writeFileSync(
    out,
    `${buildHeader(name)}\n/* Common: primitive + semantic + global */\n${commonCss}\n${componentCss}`,
  );
  console.log(`Wrote ${out} (${COMPONENTS.length} components).`);
}

fs.mkdirSync(OUT_DIR, { recursive: true });
for (const entry of PRESETS) {
  generate(entry);
}
